name: bottom_sheet_search
description: "A bottom sheet search widget for flutter"
version: 1.0.0
homepage: https://github.com/hberkayozdemir/bottom_sheet_search
repository: https://github.com/hberkayozdemir/bottom_sheet_search
environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


